# Default values for egeria-lineage.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  egeria:
    # The userid used for admin ops (no security enabled by default)
    user: garygeeke
  kafka:
    # if autoCreateTopics is set to false, the needed topics will be generated via strimzi CRDs
    config:
      autoCreateTopics: true
    external: false
    security:
      enabled: false
      protocol: SSL
      keystoreLocation: keystore.jks
      keystorePassword: keystore.pass
      truststoreLocation: truststore.jks
      truststorePassword: truststore.pass
      secretTag: f5899c937d
  image:
    configure:
      name: egeria-configure
    kubectl:
      # corporate proxy or nexus server
      registry: docker.io
      name: "bitnami/kubectl"
      tag: "latest"

replicaCount: 1


imageDefaults:
  registry: quay.io
  namespace: odpi
  tag: latest

image:
  repository: "egeria/egeria-lineage"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"
  project: egeria

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Standard helm best practice
rbac:
  # Specifies whether RBAC resources should be created
  create: true

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# Specific processing features 
options:
  jobs:
    config:
      # Timeout for configuration job
      backOffLimit: 60
      # Default will be true, but during dev set to false
      # This setting will control if the k8s job (and hence pod/logs) are deleted after egeria configuration
      # Set to false to assist in debugging 
      jobdelete: true
      # If set to true helm install will not complete successfully until configuration is complete
      usehook: false

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 0

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 9443

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: lineage-sample.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - lineage-sample.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 2000m
  #   memory: 1024Mi
  # requests:
  #   cpu: 2000m
  #   memory: 1024Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

lineage:
  # Whether a default configuration is performed or not. 
  # Defaults to true
  config: true
  version: "4.0-prelease.0"
  # this topic will be created using the strimzi CRD
  # and its name will be the concatenation of the topic.prefix and topic.name seperated with a dot "."
  # e.g. <topic.prefix>.<topic.name>
  topic:
    name: replication-metadata
    prefix: itg
    options:
      replicas: 1
      partitions: 1
      config:
        retention:
          ms: "604800000"
  consumerId: metadata.consumer
  serverName: cocoMDS1

nodeSelector: {}

tolerations: []

affinity: {}

# Allows to deploy the egeria base with the sample integration lineage event driven connector (egeria-base)
# Defaults to false
egeria-base:
  enabled: false
