{{ if not .Values.global.kafka.external }}
# SPDX-License-Identifier: Apache-2.0
  # Copyright Contributors to the Egeria project.
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Release.Name }}-strimzi
spec:
  kafka:
    version: {{ .Values.strimzi.kafka.version }}
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
{{ if .Values.strimzi.kafka.listeners.external.enabled }}
      - name: external
        port: {{ .Values.global.kafka.listenerPort }}
        type: nodeport
        tls: false
        configuration:
          bootstrap:
            nodePort: {{ .Values.strimzi.kafka.listeners.external.bootstrapNodePort }}
          brokers:
          - broker: 0
            advertisedHost: {{ .Values.strimzi.kafka.listeners.external.advertisedHost }}
{{ end }}
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      auto.create.topics.enable: "{{ .Values.global.kafka.config.autoCreateTopics }}"
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    storage:
      type: persistent-claim
      size: 5Gi
      deleteClaim: true
      {{- if .Values.storageClassName }}
      class: {{ .Values.storageClassName }}
      {{- end }}
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: true
      {{- if .Values.storageClassName }}
      class: {{ .Values.storageClassName }}
      {{- end }}
  entityOperator:
    topicOperator:
      reconciliationIntervalSeconds: 5
    userOperator: 
      reconciliationIntervalSeconds: 20
{{ end }}
