# SPDX-License-Identifier: Apache-2.0
  # Copyright Contributors to the Egeria project.
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Release.Name }}-strimzi
spec:
  kafka:
    version: {{ .Values.kafka.version }}
    replicas: {{ .Values.kafka.replicas }}
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      auto.create.topics.enable: "true"
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    storage:
      type: persistent-claim
      size: 5Gi
      deleteClaim: true
      {{- if .Values.storageClassName }}
      class: {{ .Values.storageClassName }}
      {{- end }}
    resources: {{ .Values.kafka.resources | toYaml | nindent 6 }}
  zookeeper:
    replicas: {{ .Values.zookeeper.replicas }}
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: true
      {{- if .Values.storageClassName }}
      class: {{ .Values.storageClassName }}
      {{- end }}
    resources: {{ .Values.zookeeper.resources | toYaml | nindent 6 }}
  entityOperator:
    topicOperator:
      reconciliationIntervalSeconds: 20
    userOperator: 
      reconciliationIntervalSeconds: 20
